%-------------------------------------------------------------
%  Final Project of OMBAE PhD course, Winter semester 2011/12
%
%  Author: Nuno Miguel Leite, No. 59734/D
%-------------------------------------------------------------
function Data = importfile(fileToRead)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 06-Feb-2012 17:55:08

% Import the file
sheetName = 'Relacoes';
[numbers, strings] = xlsread(fileToRead, sheetName);
if ~isempty(numbers)
    newData.data =  numbers;
end
if ~isempty(strings)
    newData.textdata =  strings;
end

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData);
for i = 1 : length(vars)
    assignin('base', vars{i}, newData.(vars{i}));
end

%newData.data

%newData.textdata

% Windows
% names = [newData.textdata(2, 2:size(newData.textdata, 2))]
% Dim = size(newData.data, 1);
% Dim1 = size(newData.data, 2);
% size(names, 2);
% 
% % Class names
% Classes = [names(1:Dim-1)];
% 
% ConflictMatrix = newData.data(1:Dim-1, 1:Dim-1);
% % Replace NaN by zero
% indexes = isnan(ConflictMatrix);
% ConflictMatrix(indexes) = 0;
% 
% Data.ConflictMatrix = ConflictMatrix;
% Data.Classes = Classes;


% Linux - Chose first column
names = [newData.textdata(3:size(newData.textdata, 1)-1, 1)];

%pause

Dim = size(newData.data, 1);
% Dim1 = size(newData.data, 2);
%size(names, 2)

%newData.data
%pause

% Class names
Classes = names;

ConflictMatrix = newData.data(3:Dim-1, 1:Dim-3);
%ConflictMatrix


%size(ConflictMatrix)
%size(names)

%pause
% Replace NaN by zero
indexes = isnan(ConflictMatrix);
ConflictMatrix(indexes) = 0;

Data.ConflictMatrix = ConflictMatrix;
Data.Classes = Classes;

